export interface DataRecord {
  band: string;
  member: string;
  role: string;
  context: string;
  citations: string;
}

export const DATA: DataRecord[] = [
  { band: "Lira Unión", member: "Horacio Valencia Arango", role: "Director", context: "Orquesta preferida por los medellinenses", citations: "[1]" },
  { band: "Lira Unión", member: "Nicolás Torres", role: "Colaboración en Dirección", context: "Orquesta preferida por los medellinenses", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Nicolás Torres", role: "Director", context: "General", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Julián Restrepo", role: "Vocalista", context: "General", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Samuel Martínez", role: "Vocalista", context: "General", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Augusto Trespalacios", role: "Vocalista", context: "General", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Obdulio Sánchez", role: "Vocalista", context: "General", citations: "[1]" },
  { band: "Jazz Nicolás", member: "Nicolás Torres Baena", role: "Mandolina, Director", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Enrique Castro", role: "Violín", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Enrique Suárez", role: "Flauta", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Jaime Santamaría", role: "Piano", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Juan de Dios Durán", role: "Saxofón", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Efraín Osorio", role: "Bombardino", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Jorge Marín Vieco", role: "Saxofón", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Luis López", role: "Bajo", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Arturo Salazar", role: "Batería", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Samuel Martínez", role: "Bajo", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Emilio \"Millo\" Velásquez", role: "Contrabajo de viento", context: "1924 Formation (Founded 1920)", citations: "[2]" },
  { band: "Jazz Nicolás", member: "Nicolás Torres Baena", role: "Batería, Director", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Abel Arenas", role: "Guitarra, Cantante", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Nicolás Torres Santamaría (hijo)", role: "Piano", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "José Torres Santamaría", role: "Violín", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Lino Echeverry", role: "Trompeta", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Francisco Muñoz", role: "Trompeta", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "\"Solanilla\"", role: "Contrabajo, Tuba", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Marco Antonio Ríos", role: "Saxofón", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Juan de Dios Durán", role: "Saxofón", context: "1937 Formation", citations: "[3]" },
  { band: "Jazz Nicolás", member: "Enrique Giraldo Botero", role: "Saxofón", context: "1937 Formation", citations: "[3]" },
  { band: "Orquesta de Jorge Marín Vieco", member: "Jorge Marín Vieco", role: "Maestro, Director", context: "1936 Formation", citations: "[4]" },
  { band: "Orquesta de Jorge Marín Vieco", member: "Arturo Salazar", role: "Músico", context: "1936 Formation", citations: "[4]" },
  { band: "Orquesta de Gonzalo Vidal", member: "Gonzalo Vidal", role: "Director, Poeta, Compositor", context: "Música del 30 y 40", citations: "[4]" },
  { band: "Juan Manuel y sus Vagabundos", member: "Don Juan Abarca", role: "Pianista, Director", context: "Década del 40", citations: "[5]" },
  { band: "Orquesta Tropical", member: "Nicolás Torres", role: "Pianista, Director", context: "1946 Formation", citations: "[5, 6]" },
  { band: "Orquesta Tropical", member: "José Pérez Pérez", role: "Saxofón", context: "1946 Formation", citations: "[6]" },
  { band: "Orquesta Tropical", member: "José Machado", role: "Saxofón tenor", context: "1946 Formation", citations: "[6]" },
  { band: "Orquesta Tropical", member: "Enrique Gallego", role: "Saxofón alto", context: "1946 Formation", citations: "[6]" },
  { band: "Orquesta Tropical", member: "Enrique Giraldo \"El Matón\"", role: "Saxofón tenor", context: "1946 Formation", citations: "[6]" },
  { band: "Orquesta Tropical", member: "César Sepúlveda", role: "Trompeta", context: "1946 Formation", citations: "[6]" },
  { band: "Orquesta Tropical", member: "José Rodríguez \"Lapri\"", role: "Trompeta", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Tropical", member: "José Escobar", role: "Trombón", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Tropical", member: "\"Lucho\" Torres", role: "Batería", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Tropical", member: "Jaime Gallego", role: "Bajo", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Tropical", member: "Gerardo Vélez \"Camán\"", role: "Cantante romántico", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Tropical", member: "Valedor Ramírez", role: "Cantante tropical", context: "1946 Formation", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "Jesús Rincón", role: "Piano", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "Jaime Gallego", role: "Contrabajo", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "\"Lucho\" Torres", role: "Batería", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "César Sepúlveda", role: "Trompeta", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "Arsenio Montes", role: "Trombón", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "José Pérez Pérez", role: "Saxofón", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "Jorge Ochoa", role: "Cantante romántico", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Swing Stars", member: "Arturo Zuluaga", role: "Cantante rítmico", context: "Orquesta de planta (c. 1949)", citations: "[7]" },
  { band: "Orquesta Rítmica", member: "Enrique Giraldo \"El Matón\"", role: "Saxofón", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Efraín Herrera", role: "Saxofón", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "José Machado", role: "Saxofón", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Gerardo Bedoya", role: "Trompeta", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Fabio Bedoya", role: "Trompeta ocasional", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Gerardo Vélez", role: "Cantante", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Valedor Ramírez", role: "Cantante", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Pastor Góngora", role: "Batería", context: "c. 1950 Formation (El Campín)", citations: "[8]" },
  { band: "Orquesta Rítmica", member: "Arturo Villa", role: "Banjo", context: "c. 1950 Formation (El Campín)", citations: "[9]" },
  { band: "Orquesta Rítmica", member: "Emilio Velásquez", role: "Bajo", context: "c. 1950 Formation (El Campín)", citations: "[9]" },
  { band: "Orquesta Rítmica", member: "Arsenio Montes", role: "Bajo (en ocasiones)", context: "c. 1950 Formation (El Campín)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Álvaro Rojas", role: "Saxofón", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Francisco Castrillón", role: "Trompeta", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Manuel Salvador \"Lito\" Paniagua", role: "Guitarra", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Ovidio Morales", role: "Bongos", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Gildardo Álvarez", role: "Batería", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Jesús \"Chucho\" Paniagua", role: "Bajo", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Los Estudiantes", member: "Arturo Zuluaga", role: "Cantante", context: "1953 Formation (Club de Profesionales)", citations: "[9]" },
  { band: "Orquesta de Adolfo Moncada", member: "Adolfo Moncada", role: "Saxofón, Clarinete, Director", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "Roberto Lambraño", role: "Saxofón", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "Antonio Criales", role: "Saxofón, Clarinete, Vibráfono", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "\"El Ciego\" García (bogotano)", role: "Piano", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "Félix Mercado", role: "Cantante, Bongos", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "\"El niño\" Cervantes", role: "Batería", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "\"El Gran Javao\"", role: "Cantante", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta de Adolfo Moncada", member: "\"El Neñe\" Vásquez", role: "Bajo", context: "Década del 50", citations: "[10]" },
  { band: "Orquesta Medellín", member: "Fabio Bedoya", role: "Trompetista (Founder)", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Enrique Giraldo \"El Matón\"", role: "Saxofón tenor", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Abraham Sánchez", role: "Bajo", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Ramón Paniagua", role: "Saxofón", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Pablo Cuellar \"Fernando del Cairo\"", role: "Cantante", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Jesús Londoño", role: "Músico", context: "General Formation", citations: "[11]" },
  { band: "Orquesta Medellín", member: "Arturo Zuluaga", role: "Cantante", context: "General Formation", citations: "[12]" },
  { band: "Orquesta Medellín", member: "Alfonso Guerrero", role: "Batería", context: "General Formation", citations: "[12]" },
  { band: "Orquesta Medellín", member: "Mario Bedoya (primo de Fabio)", role: "Pianista", context: "General Formation", citations: "[12]" },
  { band: "Los Ases del Ritmo", member: "Arturo Zuluaga", role: "Cantante, Compositor, Líder", context: "Initial Formation (after Orquesta Medellín)", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "Ramón Paniagua", role: "Saxofón", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "\"Chucho\" Paniagua", role: "Bajo (hermano de Ramón)", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "Guillermo Arenas", role: "Batería", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "Jorge Castrillón", role: "Saxofón", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "Miguel Oviedo", role: "Trompeta", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "César Sepúlveda", role: "Trompeta", context: "Initial Formation", citations: "[13]" },
  { band: "Los Ases del Ritmo", member: "Nicolás Torres", role: "Piano", context: "Reinforcement for Casabe (Dec 22 - Jan 2)", citations: "[14]" },
  { band: "Los Ases del Ritmo", member: "Rubén Ramírez", role: "Saxofonista", context: "Reinforcement for Casabe (Dec 22 - Jan 2)", citations: "[14]" },
  { band: "Los Ases del Ritmo", member: "Ovidio Morales", role: "Bongos", context: "Reinforcement for Casabe (Dec 22 - Jan 2)", citations: "[14]" },
  { band: "Los Ases del Ritmo", member: "Arturo Alzate", role: "Trompeta, Bombardino", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Javier Ortega", role: "Acordeón, Piano, (a veces) Saxo", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Norbey Rincón", role: "Cantante", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Francisco Valencia \"Pacho\"", role: "Cantante", context: "Época Fuerte", citations: "[15, 16]" },
  { band: "Los Ases del Ritmo", member: "Saúl Orrego (fallecido)", role: "Cantante", context: "Initial/Stronger period", citations: "[16]" },
  { band: "Los Ases del Ritmo", member: "Héctor Jaramillo", role: "Guitarra", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Hernán Posada", role: "Bajo", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Fernando Ortega", role: "Batería", context: "Época Fuerte", citations: "[15]" },
  { band: "Los Ases del Ritmo", member: "Hijo de Antonio María Peñaloza", role: "Batería incipiente", context: "Early formation", citations: "[16]" },
  { band: "Los Ases del Ritmo", member: "\"Cholo\" Gallardo", role: "Saxofón (Tocó por un año)", context: "Collaborator/Recording", citations: "[17]" },
  { band: "Los Ases del Ritmo", member: "Enrique Aguilar", role: "Guitarra bajo (Innovación en grabación Codiscos)", context: "Recording", citations: "[17]" },
  { band: "Los Chivíricos", member: "Aquileo Paniagua", role: "Trompeta", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Los Chivíricos", member: "\"Mambo\" González", role: "Trompeta, Director", context: "1950s (Tejicondor)", citations: "[18, 19]" },
  { band: "Los Chivíricos", member: "Alberto Rodríguez", role: "Saxofón, Clarinete", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Los Chivíricos", member: "Luis Carlos Zapata", role: "Guitarra", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Los Chivíricos", member: "Manuel Gil", role: "Contrabajo", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Los Chivíricos", member: "Miguel Zapata", role: "Cantante", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Los Chivíricos", member: "José Múnera", role: "Batería", context: "1950s (Tejicondor)", citations: "[18]" },
  { band: "Orquesta Antillana Club", member: "Fabián González", role: "Guitarra eléctrica", context: "After renaming/addition of members", citations: "[18]" },
  { band: "Sexteto Miramar", member: "Hugo Gil \"Chamizo\"", role: "Congas, Timbales", context: "Formation 1 (Barranquilla) / Formation 3 (Modernized)", citations: "[20-22]" },
  { band: "Sexteto Miramar", member: "Rubén Darío \"El Mago\"", role: "Músico / Guitarra eléctrica (F3)", context: "Formation 1 (Barranquilla) / Formation 3 (Modernized)", citations: "[20, 22]" },
  { band: "Sexteto Miramar", member: "Edgar Quintero", role: "Músico", context: "Formation 1 (Barranquilla)", citations: "[20]" },
  { band: "Sexteto Miramar", member: "Hernán Builes", role: "Músico / Bajo, Dirección (F3)", context: "Formation 1 (Barranquilla) / Formation 3 (Modernized)", citations: "[20, 22]" },
  { band: "Sexteto Miramar", member: "Mabel", role: "Músico", context: "Formation 1 (Barranquilla)", citations: "[20]" },
  { band: "Sexteto Miramar", member: "William Jaramillo", role: "Músico", context: "Formation 1 (Barranquilla)", citations: "[20]" },
  { band: "Sexteto Miramar", member: "Héctor Quintero", role: "Vibráfono, Saxofón", context: "Formation 3 (Modernized)", citations: "[22]" },
  { band: "Sexteto Miramar", member: "Rodolfo Aicardi", role: "Cantante", context: "Formation 3 (Modernized)", citations: "[22]" },
  { band: "Sexteto Miramar", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "Formation 3 (Modernized)", citations: "[22]" },
  { band: "Sexteto Miramar", member: "Jhonny Moré (de Cartagena)", role: "Cantando (Grabación de LP)", context: "Grabación", citations: "[23]" },
  { band: "Orquesta de Tita Duval", member: "Tita Duval", role: "Cantante, Saxofonista, Directora", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "Aida \"Barco\" (hija de Tita)", role: "Saxofonista", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "Mirta (sobrina de Tita)", role: "Congas, Güiro, Batería (algo de)", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "Roberto Rey Jr. \"Cuto\"", role: "Trompeta", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "Darío Restrepo", role: "Piano", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "Rodrigo", role: "Bajo", context: "General Formation", citations: "[24]" },
  { band: "Orquesta de Tita Duval", member: "William Jaramillo", role: "Batería", context: "General Formation (Baterista por dos años)", citations: "[24]" },
  { band: "Los Falcons", member: "William Jaramillo", role: "Batería", context: "Grabación de La Cumbia de Sal y Despeinada", citations: "[25]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Raúl López (Q.E.P.D.)", role: "Cantante", context: "Four-year formation", citations: "[26]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Ricaurte Arias", role: "Saxofón, Clarinete, Director", context: "Four-year formation", citations: "[26]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Gerardo Bedoya", role: "Trompeta", context: "Four-year formation / Alternate Formation", citations: "[26, 27]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "José Álvarez (Q.E.P.D.)", role: "Trompeta", context: "Four-year formation", citations: "[26]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Carlos Correa", role: "Piano", context: "Four-year formation", citations: "[26]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "William Jaramillo", role: "Batería", context: "Four-year formation / Alternate Formation", citations: "[26, 27]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Horacio Bedoya", role: "Tumbadora (solo sábados, no había bajo)", context: "Four-year formation", citations: "[28]" },
  { band: "Orquesta de Ricaurte Arias (Jardín Pilsen)", member: "Fredy Ferrer (Q.E.P.D.)", role: "Tumbadora (also played)", context: "Four-year formation", citations: "[28]" },
  { band: "Orquesta de Ricaurte Arias (Alternate Formation)", member: "Óscar \"El Gago\" Sepúlveda", role: "Trompeta", context: "Alternate Formation", citations: "[27]" },
  { band: "Orquesta de Ricaurte Arias (Alternate Formation)", member: "Un hermano de Gabriel Uribe", role: "Piano", context: "Alternate Formation", citations: "[27]" },
  { band: "Orquesta de Ricaurte Arias (Alternate Formation)", member: "\"Guayaba\"", role: "Músico (poco recordado)", context: "Alternate Formation", citations: "[27]" },
  { band: "Orquesta de Ricaurte Arias (Recording Session)", member: "Jairo Gómez", role: "Bongoes (Ayuda en grabaciones de boleros)", context: "Recording Sessions", citations: "[29]" },
  { band: "Orquesta de Ricaurte Arias (Recording Session)", member: "\"El Cholo\" Gallardo", role: "Clarinete (en Fiestas)", context: "Recording Sessions", citations: "[29]" },
  { band: "Orquesta de Ricaurte Arias (Recording Session)", member: "Edmundo Arias", role: "Bajo (en Fiestas)", context: "Recording Sessions", citations: "[29]" },
  { band: "Orquesta de Ricaurte Arias (Recording Session)", member: "\"Mono\" Díaz", role: "Batería (creído en Fiestas)", context: "Recording Sessions", citations: "[29]" },
  { band: "Trío Los Caribeños", member: "Jhonny Ferrer", role: "Músico", context: "General Formation", citations: "[28]" },
  { band: "Trío Los Caribeños", member: "Tito Ávila", role: "Músico", context: "General Formation", citations: "[28]" },
  { band: "Trío Los Caribeños", member: "Enrique Aguilar", role: "Músico", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Early Formation)", member: "Mario Erazo", role: "Bongocero (Replaced)", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Early Formation)", member: "Fabio Arroyave \"El terror de los pianistas\"", role: "Pianista", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Early Formation)", member: "Lucho Morales", role: "Maraquero (Q.E.P.D.)", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Early Formation)", member: "Alfredo Díaz (chileno)", role: "Guitarra", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Early Formation)", member: "Lucía Herrón", role: "Cantante", context: "General Formation", citations: "[28]" },
  { band: "Fantasio Grill (Later Trio)", member: "Julio García", role: "Piano, Órgano, Administrador", context: "Trio Formation (after Sexteto Miramar)", citations: "[21]" },
  { band: "Fantasio Grill (Later Trio)", member: "Teresita Rendón", role: "Cantante", context: "Trio Formation (after Sexteto Miramar)", citations: "[21]" },
  { band: "Fantasio Grill (Later Trio)", member: "William Jaramillo", role: "Batería", context: "Trio Formation (after Sexteto Miramar)", citations: "[21]" },
  { band: "Orquesta de Joimer y sus Estrellas", member: "Joimer", role: "Bajista (Director)", context: "General Formation (Itagüí)", citations: "[30]" },
  { band: "Daniel Santos Sonora", member: "(Ecuatoriano)", role: "Director", context: "Almacenes Sears Performance", citations: "[30]" },
  { band: "Daniel Santos Sonora", member: "\"Chucho\" Villegas (de Fruko y sus Tesos)", role: "Bongocero", context: "Almacenes Sears Performance", citations: "[30]" },
  { band: "Las Hermanas Rendón (Duet)", member: "Teresita Rendón", role: "Vocalista", context: "Duet Formation", citations: "[31]" },
  { band: "Las Hermanas Rendón (Duet)", member: "Rosalba Rendón (Ada Román)", role: "Vocalista", context: "Duet Formation", citations: "[31]" },
  { band: "Las Hermanas Rendón (Duet)", member: "Campo Elías", role: "Bajo (Collaborator)", context: "Duet Collaboration", citations: "[31]" },
  { band: "Las Hermanas Rendón (Duet)", member: "William Jaramillo", role: "Batería (Collaborator)", context: "Duet Collaboration", citations: "[31]" },
  { band: "Las Serranitas", member: "Dayira Calle (Hermanas Calle)", role: "Vocalista", context: "Duet Formation", citations: "[32]" },
  { band: "Las Serranitas", member: "Nelly Calle (Hermanas Calle)", role: "Vocalista", context: "Duet Formation", citations: "[32]" },
  { band: "Orquesta de Alcides Lerzundy", member: "Alcides Lerzundy", role: "Saxofonista, Director", context: "General Formation", citations: "[19]" },
  { band: "Orquesta de Alcides Lerzundy", member: "\"La Silga\" Ríos", role: "Guitarrista", context: "General Formation", citations: "[19]" },
  { band: "Orquesta de Alcides Lerzundy", member: "Miguel Ochoa", role: "Músico", context: "General Formation", citations: "[19]" },
  { band: "Orquesta de Alcides Lerzundy", member: "(Hijo de Lerzundy)", role: "Piano", context: "General Formation", citations: "[19]" },
  { band: "Los Caballeros del Ritmo", member: "Pedro Chalarca", role: "Cantante", context: "General Formation (Cierta época)", citations: "[19]" },
  { band: "Los Caballeros del Ritmo", member: "Antonio González", role: "Cantante", context: "General Formation (Cierta época)", citations: "[19]" },
  { band: "Los Caballeros del Ritmo", member: "Enrique Giraldo (Padre de los Giraldo)", role: "Saxofón, Director", context: "General Formation (Cierta época) / 1950s Detailed", citations: "[19, 33, 34]" },
  { band: "Los Caballeros del Ritmo", member: "\"Cheíto\"", role: "Bajo", context: "General Formation (Cierta época)", citations: "[19]" },
  { band: "Los Caballeros del Ritmo", member: "\"El Gato\"", role: "Trompeta", context: "General Formation (Cierta época)", citations: "[19]" },
  { band: "Los Caballeros del Ritmo", member: "Hipólito Bolívar", role: "Cantante", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Jorge Castrillón \"Pior es nada\"", role: "Saxofón", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Tiberio Hernández", role: "Saxofón", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Heraclio Paniagua", role: "Saxofón", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Abraham Sánchez \"El Tuerto\"", role: "Bajo", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Múnera \"El Culón\"", role: "Batería", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Salvador Pasos", role: "Trompeta", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Lino Álvarez", role: "Trompeta", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Palacio \"El Gato\"", role: "Trompeta", context: "1950s Detailed Formation", citations: "[35]" },
  { band: "Los Caballeros del Ritmo", member: "Mario Bedoya", role: "Pianista (Si se requería en contrato)", context: "1950s Detailed Formation (Occasional)", citations: "[36]" },
  { band: "Los Caballeros del Ritmo", member: "Elisa Peláez", role: "Cantante femenina (Acompañó muchas veces)", context: "1950s Detailed Formation (Occasional)", citations: "[36]" },
  { band: "Cataño y sus Cometas", member: "Luis Cataño", role: "Saxofonista, Líder", context: "General", citations: "[37]" },
  { band: "Los Corraleros de Majagual", member: "Nacho", role: "Músico (Joined after Joimer y sus Estrellas)", context: "General", citations: "[30]" },
  { band: "Los Corraleros de Majagual", member: "Humberto Muriel", role: "Cantante, Congas (for salsa)", context: "Early period (Joined from Sexteto Miramar)", citations: "[23]" },
  { band: "Los Corraleros de Majagual", member: "Manuel Cervantes", role: "Director, Trompeta", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Corraleros de Majagual", member: "Humberto Pabón \"Pluma\"", role: "Timbales, Batería", context: "Mexico Formation (c. 1969-1970s)", citations: "[38, 39]" },
  { band: "Los Corraleros de Majagual", member: "Un hijo del \"Cachaco\" Arango", role: "Saxofón", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Corraleros de Majagual", member: "Rosendo Martínez", role: "Trombón, Bombardino", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Corraleros de Majagual", member: "Aniceto Molina", role: "Acordeón", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Corraleros de Majagual", member: "Wilson Trujillo \"El Negrito Sabor\"", role: "Cantante", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Corraleros de Majagual", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "Mexico Formation (c. 1969-1970s)", citations: "[38]" },
  { band: "Los Ídolos", member: "\"Cholo\" Gallardo", role: "Saxo alto, Saxofón", context: "1969-1970 Formation (Músicos calificados)", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Abraham Núñez", role: "Saxo tenor, Saxofón", context: "1969-1970 Formation (Músicos calificados)", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Fruko", role: "Timbaletas, Batería", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Fernando Villegas", role: "Congas", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Jaime Ley \"Carepapa\"", role: "Bajo, Cantante, Bajista", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Mariano Sepúlveda", role: "Guitarra eléctrica, Guitarra", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Luis Fernando Mesa \"Tomate\"", role: "Solovox, Piano", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Jaime Galé", role: "Cantante", context: "1969-1970 Formation (Músicos calificados)", citations: "[40]" },
  { band: "Los Ídolos", member: "Rodolfo Aicardi", role: "Cantante", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Los Ídolos", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "1969-1970 Formation (Músicos calificados) / Formation 2", citations: "[40, 41]" },
  { band: "Sexteto Intercontinental", member: "Tomás Di Santo", role: "Director, Pianista", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Sexteto Intercontinental", member: "(Un señor veterano y fallecido)", role: "Bajo", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Sexteto Intercontinental", member: "Pedro Gutiérrez \"Secundino\"", role: "Batería", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Sexteto Intercontinental", member: "Fabio Espinoza \"Pajuelín\"", role: "Trompeta", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Sexteto Intercontinental", member: "\"Cholo\" Gallardo", role: "Saxofón", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Sexteto Intercontinental", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "Hotel Intercontinental Group", citations: "[42]" },
  { band: "Los Profetas", member: "Jaime Galé", role: "Líder", context: "General Formation", citations: "[39]" },
  { band: "El Combo de las Estrellas", member: "Álvaro Velásquez", role: "Timbaletas, Founder", context: "1974 Formation (Codiscos)", citations: "[43, 44]" },
  { band: "El Combo de las Estrellas", member: "Jairo Paternina", role: "Cantante, Founder", context: "1974 Formation (Codiscos)", citations: "[43, 44]" },
  { band: "El Combo de las Estrellas", member: "May González", role: "Bajo, Cantante", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Diego del Real", role: "Piano", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Luis Fernando Mesa \"Tomate\"", role: "Piano (Posteriormente)", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Freddy Herrera (fallecido)", role: "Trombón", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Reinaldo Carreño", role: "Trompeta", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Germán (hermano de Reinaldo)", role: "Trompeta", context: "1974 Formation (Codiscos)", citations: "[44]" },
  { band: "El Combo de las Estrellas", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "Joined two months after formation", citations: "[43]" },
  { band: "Los Hermanos Martelo", member: "Carlos Martelo", role: "Director, Líder (Tío)", context: "Medellín/El Rodeo (c. 1965)", citations: "[45, 46]" },
  { band: "Los Hermanos Martelo", member: "Narciso Martelo", role: "Trompetista (Tío)", context: "Medellín/El Rodeo (c. 1965)", citations: "[45, 46]" },
  { band: "Los Hermanos Martelo", member: "José Joaquín Martelo", role: "Bajista (Tío)", context: "Medellín/El Rodeo (c. 1965)", citations: "[45, 46]" },
  { band: "Los Hermanos Martelo", member: "Alberto Martelo", role: "Saxofonista (Hermano mayor)", context: "Medellín/El Rodeo (c. 1965)", citations: "[45]" },
  { band: "Los Hermanos Martelo", member: "Álvaro Rojas", role: "Músico residente", context: "Medellín/El Rodeo (c. 1965) (Local musician)", citations: "[45]" },
  { band: "Los Hermanos Martelo", member: "Maestro Orejuela", role: "Trombonista", context: "Medellín/El Rodeo (c. 1965) (Local musician)", citations: "[45]" },
  { band: "Los Hermanos Martelo", member: "Maestro Herrera", role: "Músico (Maestro)", context: "Medellín/El Rodeo (c. 1965) (Local musician)", citations: "[45]" },
  { band: "Los Hermanos Martelo", member: "\"El Mono\" Ospina", role: "Saxofonista, Profesor", context: "Medellín/El Rodeo (c. 1965) (Local musician)", citations: "[45, 46]" },
  { band: "Los Hermanos Martelo", member: "Hermídez Benítez", role: "Baterista", context: "Medellín/El Rodeo (c. 1965)", citations: "[45]" },
  { band: "Los Hermanos Martelo", member: "Gabriel Romero", role: "Cantante (Grabó en sello Victoria)", context: "Recording/Vocalist", citations: "[47]" },
  { band: "Los Hermanos Martelo", member: "Hernando Barbosa", role: "Cantante", context: "Recording/Vocalist", citations: "[46, 47]" },
  { band: "Los Hermanos Martelo", member: "Juan Piña", role: "Cantante", context: "Recording/Vocalist", citations: "[46, 47]" },
  { band: "Los Hermanos Martelo", member: "Flor del Valle (Shirley Rincón)", role: "Vocalista", context: "Recording/Vocalist", citations: "[16, 27, 47]" },
  { band: "Los Hermanos Martelo", member: "María Helena (Fallecida)", role: "Vocalista", context: "Recording/Vocalist", citations: "[46, 47]" },
  { band: "Los Hermanos Martelo", member: "Eliseo Herrera", role: "Rey del trabalenguas (Interpretó temas en LP)", context: "Recording/Collaborator", citations: "[47]" },
  { band: "Los Hermanos Martelo", member: "Alfredo Gutiérrez", role: "Acordeonero (Cantó algunos temas)", context: "Recording/Collaborator", citations: "[47]" },
  { band: "Los Hermanos Martelo", member: "Jorge Gaviria", role: "Trompeta", context: "General (Referenced)", citations: "[46]" },
  { band: "Los Hermanos Martelo", member: "Salvador Pasos", role: "Trompeta", context: "General (Referenced)", citations: "[46]" },
  { band: "Los Hermanos Martelo", member: "Apolo Gómez (sobrino de Antonio María Peñaloza)", role: "Trombón", context: "General (Referenced)", citations: "[46]" },
  { band: "Los Martelo Juniors", member: "Rafael Martelo", role: "Saxofón (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Juan Martelo", role: "Saxofón (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Carlos Emilio Martelo", role: "Batería (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Carlos Arturo Martelo", role: "Piano (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Carlos Julio Martelo", role: "Saxofón (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Jesús Martelo", role: "Bajo (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Pedro Martelo", role: "Trombón (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Ricardo Martelo", role: "Trombón, Trompeta (Hermano)", context: "Third Orchestra", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Jairo Perea", role: "Cantante", context: "Third Orchestra (Non-brother)", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Arnulfo Tamayo", role: "Cantante", context: "Third Orchestra (Non-brother)", citations: "[49]" },
  { band: "Los Martelo Juniors", member: "Hija de Levys Benítez", role: "Cantante", context: "Third Orchestra (Non-brother)", citations: "[49]" },
  { band: "Los Claves", member: "Alberto Sánchez", role: "Saxofón tenor", context: "Initial/Innovating Formation", citations: "[50]" },
  { band: "Los Claves", member: "Jorge Juan Mejía", role: "Guitarra, Canto", context: "Initial/Innovating Formation", citations: "[50]" },
  { band: "Los Claves", member: "Jaime Ley", role: "Bajo, Canto", context: "Initial/Innovating Formation", citations: "[50]" },
  { band: "Los Claves", member: "Henry Giraldo", role: "Solovox, Órgano", context: "Initial/Innovating Formation (Hermano)", citations: "[50]" },
  { band: "Los Claves", member: "Óscar Giraldo", role: "Saxofón", context: "Initial/Innovating Formation", citations: "[50]" },
  { band: "Los Claves", member: "Dos hermanos del speaker", role: "Percusión", context: "Initial/Innovating Formation (Trained by Nicolás Cervantes)", citations: "[50]" },
  { band: "New Stars Club", member: "José Jiménez", role: "Solovox (Reemplazó a Laureano Gómez)", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Luis Carlos Gómez", role: "Dueño del grupo, Cantante", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Dayro Maso", role: "Abogado, Cantante", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Édgar Pérez (fallecido)", role: "Baterista", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Elías Villegas", role: "Bajo", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Freddy Franklin \"Gringo\"", role: "Saxofonista", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Rodrigo", role: "Tumbadora", context: "General Formation", citations: "[51]" },
  { band: "New Stars Club", member: "Mariano Sepúlveda", role: "Guitarra", context: "General Formation", citations: "[51]" },
  { band: "Los Superiores", member: "May González", role: "Bajo, Cantante", context: "Jardín Pilsen Formation (Formed with Alfonso Piña)", citations: "[52]" },
  { band: "Los Superiores", member: "Héctor Suárez", role: "Saxofón, Clarinete", context: "Jardín Pilsen Formation", citations: "[52]" },
  { band: "Los Superiores", member: "Alfonso Piña", role: "Saxofón, Clarinete, Líder (Partner)", context: "Jardín Pilsen Formation", citations: "[52, 53]" },
  { band: "Los Superiores", member: "Gallego (hermano menor de Fabio)", role: "Batería", context: "Jardín Pilsen Formation", citations: "[52]" },
  { band: "Los Superiores", member: "Wilson Peña", role: "Tumbadora", context: "Jardín Pilsen Formation", citations: "[52]" },
  { band: "Los Superiores", member: "Mariano Sepúlveda", role: "Piano, Guitarra", context: "Jardín Pilsen Formation", citations: "[52]" },
  { band: "Los Grecos", member: "Luis Carlos Montoya", role: "Director, Arreglista, Saxofón alto", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Pablo Emilio Ospina", role: "Cantante", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Juan José Henao", role: "Cantante", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Carlos Ospina", role: "Batería", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Fabio Agudelo", role: "Saxo tenor", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Édgar Ávila (fallecido)", role: "Guitarra (punteaba muy bien)", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Tobías", role: "Congas", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Leonardo", role: "Trombonista", context: "General Formation", citations: "[54]" },
  { band: "Los Grecos", member: "Alfonso Monsalve", role: "Organeta", context: "General Formation", citations: "[54]" },
  { band: "Helenita Vargas Recording Group", member: "Al Díaz", role: "Trompeta", context: "Recording Pasaste a la Historia", citations: "[55]" },
  { band: "Helenita Vargas Recording Group", member: "Rafael Ortiz", role: "Guitarra", context: "Recording Pasaste a la Historia", citations: "[55, 56]" },
  { band: "Helenita Vargas Recording Group", member: "Lito Paniagua", role: "Guitarra", context: "Recording Pasaste a la Historia", citations: "[55, 56]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Luiggi Negri", role: "Violín, Clarinete, Saxofón", context: "Initial Formation (Italian musicians)", citations: "[57]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Adolfo Podestá", role: "Violín, Clarinete, Saxofón", context: "Initial Formation (Italian musicians)", citations: "[57, 58]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Antonio Testoni", role: "Violín, Clarinete, Saxofón tenor", context: "Initial Formation (Italian musicians)", citations: "[57, 58]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Luiggi Mainardi", role: "Violonchelo, Saxofón", context: "Initial Formation (Italian musicians)", citations: "[57, 58]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Gualtiero Barbieri", role: "Contrabajo, Acordeón, Fagot, Bajista italiano", context: "Initial Formation (Italian musicians)", citations: "[57-59]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Guillermo González", role: "Trompeta, Director", context: "Initial Formation", citations: "[57, 60]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Alfonso Gutiérrez", role: "Trompeta", context: "Initial Formation", citations: "[57]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Carlos González", role: "Piano", context: "Initial Formation", citations: "[57]" },
  { band: "Guillermo González y su Orquesta / Italian Jazz", member: "Daniel Rodríguez", role: "Cantante", context: "Initial Formation", citations: "[57]" },
  { band: "Italian Jazz", member: "Licho Almario", role: "Percusión (congas, maracas, guacharaca, batería, guache, etc.)", context: "Época de oro / General", citations: "[58, 60, 61]" },
  { band: "Italian Jazz", member: "\"Cacique\"", role: "Baterista (Gran lector musical)", context: "General", citations: "[60]" },
  { band: "Italian Jazz", member: "Solécito", role: "Músico", context: "Época de oro", citations: "[58]" },
  { band: "Italian Jazz", member: "Ananías", role: "Músico", context: "Época de oro", citations: "[58]" },
  { band: "Italian Jazz", member: "León Cardona", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Iván Uribe", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Efraín Moreno", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Antonio González", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Frank Cortés", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Nubia Ordóñez", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Italian Jazz", member: "Arsenio Montes", role: "Músico (Para grabaciones)", context: "Recording Collaborator", citations: "[58]" },
  { band: "Atlántico Jazz Band", member: "Alfonso Mesa", role: "Pianista (Initial/Replaced)", context: "Pre-1953 Formation (Required reading)", citations: "[62]" },
  { band: "Almendra Tropical", member: "Tito Sabal (santandereano)", role: "Director, Saxofonista, Músico de jazz", context: "Founded 1954 (Barranquilla)", citations: "[63]" },
  { band: "Almendra Tropical", member: "Rafico Valera", role: "Intérprete", context: "Founded 1954 (Collaborator)", citations: "[63]" },
  { band: "Almendra Tropical", member: "(Saxofonista salvadoreño)", role: "Saxofonista", context: "Founded 1954 (Collaborator)", citations: "[63]" },
  { band: "Orquesta Sonolux", member: "Gabriel Uribe", role: "Saxofón alto", context: "1960-1962 Formation / Formation 2 (Replaced by Cholo Gallardo)", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "\"Cholo\" Gallardo", role: "Saxofón alto, Saxofón", context: "1960-1962 Formation / Formation 2 (Reemplazó a Gabriel Uribe)", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Arturo \"Cachaco\" Arango", role: "Saxofón alto, Saxofón", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Álvaro Rojas", role: "Saxofón tenor, Saxofón", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Óscar Hernández", role: "Saxofón tenor, Tiplero, Arreglista", context: "1960-1962 Formation", citations: "[64-66]" },
  { band: "Orquesta Sonolux", member: "Luis Cataño", role: "Saxofón barítono, Saxofón", context: "1960-1962 Formation / Formation 2", citations: "[64-66]" },
  { band: "Orquesta Sonolux", member: "Manuel Cervantes", role: "Trompeta", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Miguel Ospino", role: "Trompeta", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Al Díaz", role: "Trompeta (Alberto Díaz el Cubano)", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Rafico Valera", role: "Trompeta, Arreglista", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Roberto Lambraño", role: "Trompeta (Alternaba en la quinta trompeta)", context: "1960-1962 Formation", citations: "[64-66]" },
  { band: "Orquesta Sonolux", member: "Arsenio Montes", role: "Trombón", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Andresito Ramos", role: "Congas, Tumbadora", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Pedro Echemendía", role: "Bajo", context: "1960-1962 Formation / Formation 2", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "\"Mono\" Hernando Díaz", role: "Batería", context: "1960-1962 Formation (One of three drummers)", citations: "[64-66]" },
  { band: "Orquesta Sonolux", member: "Reyes Cervantes (hermano de Manuel y Nicolás)", role: "Batería", context: "1960-1962 Formation / Formation 2 (One of three drummers)", citations: "[64-67]" },
  { band: "Orquesta Sonolux", member: "Manuel Gómez \"Virolí\"", role: "Batería", context: "1960-1962 Formation (One of three drummers)", citations: "[64-66]" },
  { band: "Orquesta Sonolux", member: "Antonio María Peñaloza", role: "Director, Arreglista", context: "Formation 2", citations: "[67]" },
  { band: "Orquesta Sonolux", member: "Juancho Vargas", role: "Piano", context: "Formation 2 (Alternate with Julio García)", citations: "[67]" },
  { band: "Orquesta Sonolux", member: "Julio García", role: "Piano", context: "Formation 2 (Alternate with Juancho Vargas)", citations: "[67]" },
  { band: "Orquesta Sonolux", member: "Antonio González", role: "Cantante", context: "Formation 2", citations: "[67]" },
  { band: "Orquesta Sonolux", member: "Henry Castro", role: "Cantante", context: "Formation 2", citations: "[67]" },
  { band: "Banda Marco Fidel Suárez", member: "Danilo Jiménez", role: "Bombo, Director", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Álvaro David", role: "Trompeta", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Alberto Galvis", role: "Trompeta", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Gerardo Duque", role: "Trompeta", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Juan Bautista Soto", role: "Saxofón", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Rafael Flórez", role: "Saxofón", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Octavio Alzate", role: "Bajo", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Gabriel Uribe", role: "Trombón", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Lino Durango", role: "Trombón", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Gilberto Hernández", role: "Barítono", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Enrique Suárez", role: "Percusión", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Alfonso Meneses", role: "Percusión", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Banda Marco Fidel Suárez", member: "Víctor Jiménez", role: "Percusión", context: "Grabaciones Formation (Hoy en día)", citations: "[68]" },
  { band: "Los Diplomáticos", member: "Carlos González", role: "Piano", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Juancho Vargas", role: "Piano", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Julio García", role: "Piano, Director", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Jaime Galé", role: "Batería", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Manuel Cervantes", role: "Trompeta", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Miguel Ospino", role: "Trompeta", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Castrillón", role: "Trompeta", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Álvaro Rojas", role: "Saxofón", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "\"Cholo\" Gallardo", role: "Saxofón", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Luis Cataño", role: "Saxofón", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Licho Almario", role: "Percusión, Maracas", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Antonio González", role: "Cantante", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Raúl López", role: "Cantante", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Tony Contreras", role: "Cantante", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Enrique Aguilar", role: "Bajo", context: "Detailed Formation", citations: "[69]" },
  { band: "Los Diplomáticos", member: "Pacho Zapata", role: "Órgano (Metido en la orquesta)", context: "Initial Reference", citations: "[70]" },
  { band: "Combo Di Lido", member: "William Gaviria", role: "Saxofonista", context: "Speaker's time", citations: "[46]" },
  { band: "Combo Di Lido", member: "\"El Mono\" Ospina", role: "Saxofonista", context: "Speaker's time", citations: "[46]" },
  { band: "Combo Di Lido", member: "Carlos Gaviria", role: "Bajo", context: "Speaker's time", citations: "[46]" },
  { band: "Combo Di Lido", member: "Julio García (Maestro)", role: "Piano", context: "Speaker's time", citations: "[46]" },
  { band: "Combo Di Lido", member: "Ignacio Paniagua", role: "Trompeta", context: "Speaker's time / Youth / 1974 Formation", citations: "[46, 71, 72]" },
  { band: "Combo Di Lido", member: "Jorge Gaviria", role: "Trompeta, Bajo (Youth formation)", context: "Speaker's time / Youth Formation", citations: "[46, 71]" },
  { band: "Combo Di Lido", member: "Julio Gaviria", role: "Batería", context: "Speaker's time", citations: "[46]" },
  { band: "Combo Di Lido", member: "Francisco Zumaqué", role: "Piano", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "Justo Almario", role: "Saxofón", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "Benny Márquez", role: "Cantante", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "William Gaviria", role: "Saxofón", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "\"Moncho\" Samudio", role: "Trompeta", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "Fabio Gallego \"Cicatriz\" (hermano de Jaime Galé)", role: "Batería", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "Soledad (esposa de Guillermo González)", role: "Cantante femenina", context: "Youth Formation", citations: "[71]" },
  { band: "Combo Di Lido", member: "Ricaurte Arias", role: "Director, Saxofón", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Luis Carlos Gaviria", role: "Representante, Bajo", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Jairo Vasco", role: "Saxofón tenor", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Alfonso Moyano", role: "Saxofón alto", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Néstor Izquierdo", role: "Trompeta", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "José Paniagua", role: "Trompeta", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Julio García", role: "Piano", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Combo Di Lido", member: "Pedro Julio Gaviria", role: "Batería", context: "1974 Formation (Ecuador Tour)", citations: "[72]" },
  { band: "Los Graduados", member: "(Part of Los Hispanos)", role: "Bajo, Guitarra, Tumbadora, Güiro", context: "Broke off from Los Hispanos", citations: "[74]" },
  { band: "Conjunto Miramar", member: "William Jaramillo", role: "Batería", context: "Sexteto (2nd time)", citations: "[21]" },
  { band: "Conjunto Miramar", member: "Hugo", role: "Congas", context: "Sexteto (2nd time)", citations: "[21]" },
];
