export const DATA = [
  { band: "Lira Unión", member: "Horacio Valencia Arango", role: "Director", context: "Orquesta preferida por los medellinenses" },
  { band: "Lira Unión", member: "Nicolás Torres", role: "Colaboración en Dirección", context: "Orquesta preferida por los medellinenses" },
  { band: "Jazz Nicolás", member: "Nicolás Torres", role: "Director", context: "General" },
  { band: "Jazz Nicolás", member: "Julián Restrepo", role: "Vocalista", context: "General" },
  { band: "Jazz Nicolás", member: "Samuel Martínez", role: "Vocalista", context: "General" },
  { band: "Jazz Nicolás", member: "Nicolás Torres Baena", role: "Mandolina, Director", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Enrique Castro", role: "Violín", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Enrique Suárez", role: "Flauta", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Jaime Santamaría", role: "Piano", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Juan de Dios Durán", role: "Saxofón", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Jorge Marín Vieco", role: "Saxofón", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Luis López", role: "Bajo", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Arturo Salazar", role: "Batería", context: "1924 Formation" },
  { band: "Jazz Nicolás", member: "Abel Arenas", role: "Guitarra, Cantante", context: "1937 Formation" },
  { band: "Jazz Nicolás", member: "Lino Echeverry", role: "Trompeta", context: "1937 Formation" },
  { band: "Jazz Nicolás", member: "Marco Antonio Ríos", role: "Saxofón", context: "1937 Formation" },
  { band: "Orquesta de Jorge Marín Vieco", member: "Jorge Marín Vieco", role: "Maestro, Director", context: "1936 Formation" },
  { band: "Orquesta de Jorge Marín Vieco", member: "Arturo Salazar", role: "Músico", context: "1936 Formation" },
  { band: "Orquesta Tropical", member: "Nicolás Torres", role: "Pianista, Director", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "José Pérez Pérez", role: "Saxofón", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "José Machado", role: "Saxofón tenor", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "Enrique Giraldo", role: "Saxofón tenor", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "César Sepúlveda", role: "Trompeta", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "José Escobar", role: "Trombón", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "Jaime Gallego", role: "Bajo", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "Gerardo Vélez", role: "Cantante romántico", context: "1946 Formation" },
  { band: "Orquesta Tropical", member: "Valedor Ramírez", role: "Cantante tropical", context: "1946 Formation" },
  { band: "Orquesta Swing Stars", member: "Jesús Rincón", role: "Piano", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "Jaime Gallego", role: "Contrabajo", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "César Sepúlveda", role: "Trompeta", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "Arsenio Montes", role: "Trombón", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "José Pérez Pérez", role: "Saxofón", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "Jorge Ochoa", role: "Cantante romántico", context: "c. 1949" },
  { band: "Orquesta Swing Stars", member: "Arturo Zuluaga", role: "Cantante rítmico", context: "c. 1949" },
  { band: "Orquesta Rítmica", member: "Enrique Giraldo", role: "Saxofón", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "José Machado", role: "Saxofón", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "Gerardo Bedoya", role: "Trompeta", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "Gerardo Vélez", role: "Cantante", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "Valedor Ramírez", role: "Cantante", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "Arsenio Montes", role: "Bajo", context: "c. 1950" },
  { band: "Orquesta Rítmica", member: "Emilio Velásquez", role: "Bajo", context: "c. 1950" },
  { band: "Los Estudiantes", member: "Álvaro Rojas", role: "Saxofón", context: "1953" },
  { band: "Los Estudiantes", member: "Francisco Castrillón", role: "Trompeta", context: "1953" },
  { band: "Los Estudiantes", member: "Ovidio Morales", role: "Bongos", context: "1953" },
  { band: "Los Estudiantes", member: "Arturo Zuluaga", role: "Cantante", context: "1953" },
  { band: "Orquesta Medellín", member: "Fabio Bedoya", role: "Trompetista, Founder", context: "General" },
  { band: "Orquesta Medellín", member: "Enrique Giraldo", role: "Saxofón tenor", context: "General" },
  { band: "Orquesta Medellín", member: "Abraham Sánchez", role: "Bajo", context: "General" },
  { band: "Orquesta Medellín", member: "Ramón Paniagua", role: "Saxofón", context: "General" },
  { band: "Orquesta Medellín", member: "Arturo Zuluaga", role: "Cantante", context: "General" },
  { band: "Los Ases del Ritmo", member: "Arturo Zuluaga", role: "Cantante, Líder", context: "Initial Formation" },
  { band: "Los Ases del Ritmo", member: "Ramón Paniagua", role: "Saxofón", context: "Initial Formation" },
  { band: "Los Ases del Ritmo", member: "César Sepúlveda", role: "Trompeta", context: "Initial Formation" },
  { band: "Los Ases del Ritmo", member: "Nicolás Torres", role: "Piano", context: "Reinforcement" },
  { band: "Los Ases del Ritmo", member: "Ovidio Morales", role: "Bongos", context: "Reinforcement" },
  { band: "Los Caballeros del Ritmo", member: "Enrique Giraldo", role: "Saxofón, Director", context: "1950s" },
  { band: "Los Caballeros del Ritmo", member: "Abraham Sánchez", role: "Bajo", context: "1950s" },
  { band: "Los Caballeros del Ritmo", member: "Jorge Castrillón", role: "Saxofón", context: "1950s" },
  { band: "Los Caballeros del Ritmo", member: "Gerardo Bedoya", role: "Trompeta", context: "1950s" },
  { band: "Orquesta Sonolux", member: "Álvaro Rojas", role: "Saxofón tenor", context: "1960–1962" },
  { band: "Orquesta Sonolux", member: "Manuel Cervantes", role: "Trompeta", context: "1960–1962" },
  { band: "Orquesta Sonolux", member: "Arsenio Montes", role: "Trombón", context: "1960–1962" },
  { band: "Orquesta Sonolux", member: "Luis Cataño", role: "Saxofón barítono", context: "1960–1962" },
  { band: "Orquesta Sonolux", member: "Antonio María Peñaloza", role: "Director, Arreglista", context: "Formation 2" },
  { band: "Los Ídolos", member: "Fruko", role: "Timbaletas, Batería", context: "1969–1970" },
  { band: "Los Ídolos", member: "Rodolfo Aicardi", role: "Cantante", context: "1969–1970" },
  { band: "Los Ídolos", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "1969–1970" },
  { band: "Los Ídolos", member: "Jaime Ley", role: "Bajo, Cantante", context: "1969–1970" },
  { band: "Sexteto Miramar", member: "Hugo Gil", role: "Congas, Timbales", context: "Formation 1" },
  { band: "Sexteto Miramar", member: "Hernán Builes", role: "Bajo, Dirección", context: "Formation 3" },
  { band: "Sexteto Miramar", member: "Rodolfo Aicardi", role: "Cantante", context: "Formation 3" },
  { band: "Sexteto Miramar", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "Formation 3" },
  { band: "Los Corraleros de Majagual", member: "Humberto Muriel", role: "Cantante, Congas", context: "Early period" },
  { band: "Los Corraleros de Majagual", member: "Manuel Cervantes", role: "Director, Trompeta", context: "Mexico c. 1969" },
  { band: "El Combo de las Estrellas", member: "Humberto Muriel", role: "Cantante, Tumbadora", context: "1974" },
  { band: "El Combo de las Estrellas", member: "Luis Fernando Mesa", role: "Piano", context: "1974" },
  { band: "Los Diplomáticos", member: "Álvaro Rojas", role: "Saxofón", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Manuel Cervantes", role: "Trompeta", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Arsenio Montes", role: "Trombón", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Luis Cataño", role: "Saxofón", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Julio García", role: "Piano, Director", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Antonio González", role: "Cantante", context: "Detailed Formation" },
  { band: "Los Diplomáticos", member: "Enrique Aguilar", role: "Bajo", context: "Detailed Formation" },
];
